name: flutter_itech
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  simple_animations: ^5.0.2
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Esta é a seção de configuração do Flutter.
# Todas as configurações específicas do Flutter vêm aqui.
flutter:

  # Esta linha deve estar aqui, com dois espaços antes.
  uses-material-design: true

  # A seção de assets também fica aqui, com a indentação correta.
  assets:
    - assets/imagens/