name: flutter_itech
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.9.0
  
dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  test_api: ^0.7.7
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Esta é a seção de configuração do Flutter.
# Todas as configurações específicas do Flutter vêm aqui.
flutter:

  # Esta linha deve estar aqui, com dois espaços antes.
  uses-material-design: true

  # A seção de assets também fica aqui, com a indentação correta.
  assets:
    - assets/imagens/